### ISSUE TITLE
Request: zlib support

### ISSUE THREAD

**Issue by donotdox** [xvoland/Extract#26]
Hi,

Just wanted to request adding zlib support. Sorry if this isn't the right way to ask. I came across my first .zlib file. There is a tool called zlib-flate, installed as part of qpdf that works - http://manpages.ubuntu.com/manpages/trusty/man1/zlib-flate.1.html - but of course it would be handy to have it within extract :)

Thank you

**Comment by git-em** [comment]
Here you go (:
#27

**Comment by donotdox** [comment]
Thank you very much!

I'm a real git noob so didn't know how to use git to update. However, I copied and pasted just the two lines required and it worked perfectly :)

**Comment by git-em** [comment]
Glad to know it worked, @donotdox! I had never used zlib before so it took me a while to figure it out :b
In case you need someday, the syntax for the command is:

`zlib-flate -uncompress < input_file.zlib > output_file`

You can also use with it to `-compress`. I wouldn't recommend using neither in a regular basis though. Even the `man zlib-flate` suggests that it's not a good idea. I think it's better to stick with other formats and more user-friendly programs for conventional tasks.

About git, since i just submitted the pull request, it has not been accepted by the maintainers yet, so the fastest way is either doing what you did, or cloning [my fork](https://github.com/git-em/Extract), from where i sent the changes. Once the commit is merged to this repo you can just go to your local `Extract` directory and type `git pull` to "pull" the latest version.

**Comment by xvoland** [comment]
Okay, thank you!
